-- customer data
INSERT INTO customer (name, age, email, country, join_date) VALUES ('Prakaymya Singh', 19, 'prak.singh@nushackers.org', 'IND', '2023-06-15');
INSERT INTO customer (name, age, email, country, join_date) VALUES ('John Kim', 32, 'john.kim@yahoo.com', 'SG', '2023-07-20');
INSERT INTO customer (name, age, email, country, join_date) VALUES ('Ravi Sharma', 45, 'ravi.sharma@outlook.com', 'IND', '2024-04-05');
INSERT INTO customer (name, age, email, country, join_date) VALUES ('Emily Wong', 29, 'emily.wong@gmail.com', 'AUS', '2023-09-10');
INSERT INTO customer (name, age, email, country, join_date) VALUES ('Satoshi Nakamura', 38, 'satoshi.naka@gmail.com', 'JAP', '2023-10-01');
INSERT INTO customer (name, age, email, country, join_date) VALUES ('Chen Wei', 22, 'chen.wei@gmail.com', 'SG', '2024-03-12');
INSERT INTO customer (name, age, email, country, join_date) VALUES ('Amina Rahman', 27, 'amina.rahman@gmail.com', 'BAN', '2023-12-03');
INSERT INTO customer (name, age, email, country, join_date) VALUES ('George Goeff', 50, 'ggoeff@yahoo.com', 'AUS', '2024-01-15');
INSERT INTO customer (name, age, email, country, join_date) VALUES ('Priya Desai', 60, 'priya.desai@gmail.com', 'IND', '2024-04-20');
INSERT INTO customer (name, age, email, country, join_date) VALUES ('Takashi Ito', 35, 'takashi.ito@gmail.com', 'JAP', '2024-03-05');
INSERT INTO customer (name, age, email, country, join_date) VALUES ('Min Ho', 28, 'min.ho@gmail.com', 'SG', '2024-04-22');
INSERT INTO customer (name, age, email, country, join_date) VALUES ('Hafiz Abdullah', 40, 'hafiz.abdullah@gmail.com', 'SG', '2024-03-14');
INSERT INTO customer (name, age, email, country, join_date) VALUES ('Samantha Blake', 48, 'samantha.blake@gmail.com', 'AUS', '2023-08-30');
INSERT INTO customer (name, age, email, country, join_date) VALUES ('Anwar Hussain', 52, 'anwar.hussain@gmail.com', 'BAN', '2023-09-25');
INSERT INTO customer (name, age, email, country, join_date) VALUES ('Yuki Tanaka', 31, 'yuki.tanaka@gmail.com', 'JAP', '2023-10-07');
INSERT INTO customer (name, age, email, country, join_date) VALUES ('Farah Zain', 24, 'farah.zain@gmail.com', 'MY', '2023-11-18');
INSERT INTO customer (name, age, email, country, join_date) VALUES ('Nathan Clarke', 55, 'nathan.clarke@gmail.com', 'AUS', '2023-12-21');
INSERT INTO customer (name, age, email, country, join_date) VALUES ('Arjun Verma', 63, 'arjun.verma@outlook.com', 'IND', '2024-01-09');
INSERT INTO customer (name, age, email, country, join_date) VALUES ('Seojun Park', 26, 'seojun.park@outlook.com', 'KOR', '2024-02-27');
INSERT INTO customer (name, age, email, country, join_date) VALUES ('Rina Suzuki', 47, 'rina.suzuki@outlook.com', 'JAP', '2024-03-12');
INSERT INTO customer (name, age, email, country, join_date) VALUES ('Iqbal Hossain', 37, 'iqbal.hossain@gmail.com', 'BAN', '2023-06-17');
INSERT INTO customer (name, age, email, country, join_date) VALUES ('Sophie Lim', 34, 'sophie.lim@yahoo.com', 'SG', '2023-07-28');
INSERT INTO customer (name, age, email, country, join_date) VALUES ('Daniel Carter', 42, 'daniel.carter@gmail.com', 'AUS', '2023-08-15');
INSERT INTO customer (name, age, email, country, join_date) VALUES ('Haruto Yamamoto', 30, 'haruto.yamamoto@gmail.com', 'JAP', '2023-09-06');
INSERT INTO customer (name, age, email, country, join_date) VALUES ('Nadia Ahmed', 59, 'nadia.ahmed@outlook.com', 'BAN', '2023-10-29');
INSERT INTO customer (name, age, email, country, join_date) VALUES ('Muhammad Faris', 41, 'muhammad.faris@gmail.com', 'MY', '2023-11-05');
INSERT INTO customer (name, age, email, country, join_date) VALUES ('Jisoo Lee', 20, 'jisoo.lee@gmail.com', 'KOR', '2023-12-08');
INSERT INTO customer (name, age, email, country, join_date) VALUES ('David Ong', 70, 'david.ong@gmail.com', 'SG', '2024-03-14');
INSERT INTO customer (name, age, email, country, join_date) VALUES ('Fatima Begum', 18, 'fatima.begum@gmail.com', 'BAN', '2024-02-22');
INSERT INTO customer (name, age, email, country, join_date) VALUES ('Ethan Wilson', 24, 'ethan.wilson@yahoo.com', 'AUS', '2024-03-01');
INSERT INTO customer (name, age, email, country, join_date) VALUES ('Jihoon Choi', 23, 'jihoon.choi@gmail.com', 'KOR', '2023-06-20');
INSERT INTO customer (name, age, email, country, join_date) VALUES ('Sarah Tan', 18, 'sarah.tan@gmail.com', 'SG', '2023-07-03');
INSERT INTO customer (name, age, email, country, join_date) VALUES ('Krishna Patel', 33, 'krishna.patel@gmail.com', 'IND', '2023-08-26');
INSERT INTO customer (name, age, email, country, join_date) VALUES ('William George', 46, 'william.george@gmail.com', 'AUS', '2023-09-13');
INSERT INTO customer (name, age, email, country, join_date) VALUES ('Sakura Ishikawa', 29, 'sakura.ishikawa@gmail.com', 'JAP', '2023-10-17');
INSERT INTO customer (name, age, email, country, join_date) VALUES ('George Lim', 61, 'george.lim@gmail.com', 'SG', '2023-03-27');
INSERT INTO customer (name, age, email, country, join_date) VALUES ('Zafar Uddin', 49, 'zafar.uddin@gmail.com', 'BAN', '2023-12-10');
INSERT INTO customer (name, age, email, country, join_date) VALUES ('Noah Smith', 36, 'noah.smith@outlook.com', 'AUS', '2024-01-25');
INSERT INTO customer (name, age, email, country, join_date) VALUES ('Aarav Mehta', 29, 'aarav.mehta@gmail.com', 'IND', '2024-02-05');
INSERT INTO customer (name, age, email, country, join_date) VALUES ('Hyunwoo Kang', 43, 'hyunwoo.kang@yahoo.com', 'KOR', '2024-03-14');
INSERT INTO customer (name, age, email, country, join_date) VALUES ('George Cutti', 28, 'georgec1203@yahoo.com', 'IND', '2023-04-14');
INSERT INTO customer (name, age, email, country, join_date) VALUES ('Hiroshi Nakamura', 35, 'hiroshi.n@gmail.com', 'JAP', '2023-09-20');
INSERT INTO customer (name, age, email, country, join_date) VALUES ('Priya Sharma', 22, 'priya.sharma@gmail.com', 'IND', '2024-04-05');
INSERT INTO customer (name, age, email, country, join_date) VALUES ('Michael Lee', 45, 'michael.lee@gmail.com', 'AUS', '2023-11-11');
INSERT INTO customer (name, age, email, country, join_date) VALUES ('Nurul Hassan', 31, 'nurul.hassan@yahoo.com', 'BAN', '2023-12-27');
INSERT INTO customer (name, age, email, country, join_date) VALUES ('Satoshi Kudo', 40, 'satoshi.k@gmail.com', 'JAP', '2023-06-30');
INSERT INTO customer (name, age, email, country, join_date) VALUES ('George Satya', 26, 'geo.satya@gmail.com', 'IND', '2024-02-18');
INSERT INTO customer (name, age, email, country, join_date) VALUES ('Sharman Thanmugarathnam', 40, 'sth.mug@gmail.com', 'SG', '2023-08-09');
INSERT INTO customer (name, age, email, country, join_date) VALUES ('Rajiv Menon', 29, 'rajiv.menon@gmail.com', 'IND', '2023-10-02');
INSERT INTO customer (name, age, email, country, join_date) VALUES ('Jessica Wong', 33, 'jessica.wong@yahoo.com', 'SG', '2024-03-07');

------------------------------------------

-- product data
INSERT INTO product (name, category, price, stock, num_sold, website_only) VALUES ('Running Shoes', 'apparel', 119.99, 10, 50, FALSE);
INSERT INTO product (name, category, price, stock, num_sold, website_only) VALUES ('Smartwatch', 'electronics', 249.50, 5, 100, TRUE);
INSERT INTO product (name, category, price, stock, num_sold, website_only) VALUES ('Moisturizing Cream', 'cosmetics', 29.75, 20, 200, FALSE);
INSERT INTO product (name, category, price, stock, num_sold, website_only) VALUES ('Travel Backpack', 'travel', 84.99, 15, 75, TRUE);
INSERT INTO product (name, category, price, stock, num_sold, website_only) VALUES ('Wireless Headphones', 'electronics', 179.49, 0, 150, FALSE);
INSERT INTO product (name, category, price, stock, num_sold, website_only) VALUES ('Yoga Mat', 'gym', 49.99, 12, 60, FALSE);
INSERT INTO product (name, category, price, stock, num_sold, website_only) VALUES ('Leather Wallet', 'apparel', 44.95, 0, 90, TRUE);
INSERT INTO product (name, category, price, stock, num_sold, website_only) VALUES ('Sunscreen SPF 50', 'cosmetics', 24.99, 18, 110, FALSE);
INSERT INTO product (name, category, price, stock, num_sold, website_only) VALUES ('Duffel Bag', 'travel', 59.90, 9, 80, FALSE);
INSERT INTO product (name, category, price, stock, num_sold, website_only) VALUES ('Bluetooth Speaker', 'electronics', 129.99, 0, 120, TRUE);
INSERT INTO product (name, category, price, stock, num_sold, website_only) VALUES ('Resistance Bands', 'gym', 34.75, 14, 50, FALSE);
INSERT INTO product (name, category, price, stock, num_sold, website_only) VALUES ('Ski Jacket', 'apparel', 199.99, 7, 30, TRUE);
INSERT INTO product (name, category, price, stock, num_sold, website_only) VALUES ('Face Serum', 'cosmetics', 39.49, 22, 140, FALSE);
INSERT INTO product (name, category, price, stock, num_sold, website_only) VALUES ('Luggage Set', 'travel', 299.95, 0, 60, FALSE);
INSERT INTO product (name, category, price, stock, num_sold, website_only) VALUES ('Noise Cancelling Earbuds', 'electronics', 219.99, 4, 200, TRUE);
INSERT INTO product (name, category, price, stock, num_sold, website_only) VALUES ('Gym Gloves', 'gym', 19.99, 17, 90, FALSE);
INSERT INTO product (name, category, price, stock, num_sold, website_only) VALUES ('Sneakers', 'apparel', 99.95, 0, 160, TRUE);
INSERT INTO product (name, category, price, stock, num_sold, website_only) VALUES ('BB Cream', 'cosmetics', 27.89, 12, 75, FALSE);
INSERT INTO product (name, category, price, stock, num_sold, website_only) VALUES ('Hiking Boots', 'travel', 149.50, 0, 85, TRUE);
INSERT INTO product (name, category, price, stock, num_sold, website_only) VALUES ('Power Bank', 'electronics', 49.99, 8, 190, FALSE);
INSERT INTO product (name, category, price, stock, num_sold, website_only) VALUES ('Dumbbells Set', 'gym', 74.99, 6, 40, TRUE);
INSERT INTO product (name, category, price, stock, num_sold, website_only) VALUES ('Winter Coat', 'apparel', 219.00, 11, 30, FALSE);
INSERT INTO product (name, category, price, stock, num_sold, website_only) VALUES ('Makeup Brush Set', 'cosmetics', 34.49, 20, 100, TRUE);
INSERT INTO product (name, category, price, stock, num_sold, website_only) VALUES ('Trekking Poles', 'travel', 89.99, 0, 45, FALSE);
INSERT INTO product (name, category, price, stock, num_sold, website_only) VALUES ('Laptop Stand', 'electronics', 69.95, 3, 130, FALSE);
INSERT INTO product (name, category, price, stock, num_sold, website_only) VALUES ('Pull-up Bar', 'gym', 54.50, 10, 65, FALSE);
INSERT INTO product (name, category, price, stock, num_sold, website_only) VALUES ('Casual T-shirt', 'apparel', 24.99, 30, 120, FALSE);
INSERT INTO product (name, category, price, stock, num_sold, website_only) VALUES ('Shaving Kit', 'cosmetics', 39.90, 0, 55, TRUE);
INSERT INTO product (name, category, price, stock, num_sold, website_only) VALUES ('Travel Pillow', 'travel', 19.99, 9, 70, FALSE);
INSERT INTO product (name, category, price, stock, num_sold, website_only) VALUES ('VR Headset', 'electronics', 399.99, 0, 30, TRUE);
INSERT INTO product (name, category, price, stock, num_sold, website_only) VALUES ('Jump Rope', 'gym', 14.99, 15, 100, FALSE);
INSERT INTO product (name, category, price, stock, num_sold, website_only) VALUES ('Sunglasses', 'apparel', 34.95, 0, 80, TRUE);
INSERT INTO product (name, category, price, stock, num_sold, website_only) VALUES ('Lip Balm', 'cosmetics', 9.99, 25, 150, FALSE);
INSERT INTO product (name, category, price, stock, num_sold, website_only) VALUES ('Multi-port Adapter', 'electronics', 14.99, 7, 90, FALSE);
INSERT INTO product (name, category, price, stock, num_sold, website_only) VALUES ('Portable Speaker', 'electronics', 59.99, 0, 110, TRUE);
INSERT INTO product (name, category, price, stock, num_sold, website_only) VALUES ('Compression Tights', 'apparel', 39.99, 12, 70, FALSE);
INSERT INTO product (name, category, price, stock, num_sold, website_only) VALUES ('Portable Charger', 'electronics', 59.95, 15, 180, TRUE);
INSERT INTO product (name, category, price, stock, num_sold, website_only) VALUES ('Face Cleanser', 'cosmetics', 23.49, 20, 90, FALSE);
INSERT INTO product (name, category, price, stock, num_sold, website_only) VALUES ('Rolling Suitcase', 'travel', 159.99, 0, 120, TRUE);
INSERT INTO product (name, category, price, stock, num_sold, website_only) VALUES ('Fitness Tracker', 'electronics', 129.50, 5, 200, FALSE);
INSERT INTO product (name, category, price, stock, num_sold, website_only) VALUES ('Resistance Rope', 'gym', 29.99, 10, 60, FALSE);
INSERT INTO product (name, category, price, stock, num_sold, website_only) VALUES ('Windbreaker Jacket', 'apparel', 89.95, 0, 140, TRUE);
INSERT INTO product (name, category, price, stock, num_sold, website_only) VALUES ('Lip Balm', 'cosmetics', 9.99, 25, 300, FALSE);
INSERT INTO product (name, category, price, stock, num_sold, website_only) VALUES ('Neck Pillow', 'travel', 25.50, 10, 100, FALSE);
INSERT INTO product (name, category, price, stock, num_sold, website_only) VALUES ('USB Hub', 'electronics', 34.99, 8, 110, TRUE);
INSERT INTO product (name, category, price, stock, num_sold, website_only) VALUES ('Adjustable Dumbbells', 'gym', 149.99, 3, 40, FALSE);
INSERT INTO product (name, category, price, stock, num_sold, website_only) VALUES ('Ski Pants', 'apparel', 129.99, 5, 30, TRUE);
INSERT INTO product (name, category, price, stock, num_sold, website_only) VALUES ('Eye Cream', 'cosmetics', 31.99, 18, 150, FALSE);
INSERT INTO product (name, category, price, stock, num_sold, website_only) VALUES ('Packing Cubes', 'travel', 39.99, 0, 90, FALSE);
INSERT INTO product (name, category, price, stock, num_sold, website_only) VALUES ('Gaming Mouse', 'electronics', 79.95, 7, 130, TRUE);
INSERT INTO product (name, category, price, stock, num_sold, website_only) VALUES ('Foam Roller', 'gym', 44.50, 9, 80, FALSE);
INSERT INTO product (name, category, price, stock, num_sold, website_only) VALUES ('Hooded Sweatshirt', 'apparel', 59.99, 20, 100, FALSE);
INSERT INTO product (name, category, price, stock, num_sold, website_only) VALUES ('Foundation Makeup', 'cosmetics', 37.75, 10, 160, TRUE);
INSERT INTO product (name, category, price, stock, num_sold, website_only) VALUES ('Portable Fan', 'travel', 19.99, 0, 55, FALSE);
INSERT INTO product (name, category, price, stock, num_sold, website_only) VALUES ('Mechanical Keyboard', 'electronics', 120.99, 6, 90, TRUE);

------------------------------------------
